### ISSUE TITLE
Cannot resolve macro that falls into another month

### ISSUE THREAD

**Issue by dezlov** [dezlov/pascaltz#10]
A macro for finding a week day has been adjusted for zone **Asia/Hong_Kong** in **tzdata2019b** such that the target day falls into another month, which is currently cannot be handled by PascalTZ library.

See the extracts for "Sun>=28" and "Sun>=31":

```
Rule	HK	1948	1952	-	Oct	Sun>=28	3:30s	0	-
Rule	HK	1953	1964	-	Oct	Sun>=31	3:30	0	-
```

Error raised in `MacroFirstWeekDay` function:

> No valid first week day for "Sunday" after 1952.10.28

**Comment by unihedron** [comment]
Is there any workaround for this?

**Comment by dezlov** [comment]
@unihedron It was resolved the same day, but didn't get pushed for some reason.

Please try the latest master branch.

**Comment by unihedron** [comment]
Works fine. Thanks
