### ISSUE TITLE
TimeToSeconds Range check error

### ISSUE THREAD

**Issue by JoshyFun** [dezlov/pascaltz#2]
In uPascalTZ_Tools, function TimeToSeconds:

case TwoColons of
[...]
            Hours:=StrToInt(TimeIterator.GetNextWord);
[...]

Hours is 0..23 but some rules like **'Rule Egypt 1995 2005 - Sep lastThu 24:00 0 -'** writes the time as 24:00 which will raise a range check error.

By now I surround it with **{$PUSH}{$RANGECHECKS OFF}Hours:=StrToInt(TimeIterator.GetNextWord);{$POP}** but I'm worried about possible erroneous calcs.

Note: Thank you for fixing my tons of issues :-)

**Comment by dezlov** [comment]
`TimeToSeconds` treats each time component (hours, minutes, seconds) as an integer, without limiting the range. Hours component is not actually limited to 0..23.

Also, `Hours := StrToInt('24')` can't cause a range check error.

Where did you encounter a range check error?

P.S. You must be José, thanks for the ground work ;-)

**Comment by JoshyFun** [comment]
As noted in the first post, Hour type is defined as [0..23] so it can only hold values between 0 and 23. It was defined that way just to catch this kind of "errors" like "24:64" or "-1:30" where Hour is "24" or "-1" invalid values for Hour type and seconds are "64" which is another invalid seconds value.

Turning range check off in fpc allows the code to compile as the Hour type can successfully hold the "24" value but I'm used to compile everything in debug mode with all checks on to catch unexpected overflows or range checks, and the hours in that assignment will raise the range check error.

The calculations could be fine, but until now no time zone uses the "24:00" notation or an exception should happen before, so I assume that the code was not reviewed against "24:00".

IMHO solution should be to check against "24:00" as the only valid hour outside the range "00:00" -> "23:59" instead turning range check off; maybe a "WORD" temp variable to read the StrToInt, check against "24" and if not "24", assign to "Hours" variable. The question here is "Sep lastThu 24:00" is the same as "Sep LastFri 00:00" ? I think that the answer is no, so in a future somehting like "Sep lastThu 25:00" may happen ?

P.S. Yes, I'm José, I forgot that GitHub shows the nick name only. :-)

**Comment by dezlov** [comment]
Ahh, I misunderstood, I thought of enforced range checking within the code.

` TTZHour` type can be expanded to 0..24 range without any problems. This will avoid compiler range checking errors for 24:00:00 time notation.

I am also considering adding an enforced range checking within the code, to ensure that all time patterns are strictly within 00:00:00 to 24:00:00 range.

**Comment by JoshyFun** [comment]
I suggest to not expand it as it is a very good error detection, like Hour:=Hour+1 which in most cases is safe, but in a time/date library it is dangerous as 23+1=24 which should be day+1 and time 00:00. That's the reason that originally I enforced the value ranges. If somewhere you do not need or don't like to be restricted use a different variable type, like an integer and if the calculation in wrong in some case, once you dump the integer value to the time/date field it will raise an exception (when range checks are on).

In this case use integer instead TTZHour, or any other range constrained variable like TTZExtendedHour [0..24]. The ability of pascal to catch ranges is very powerful.

Instead enforce by code, force "RangeChecks on" and all range operations are automagically controlled by fpc at a speed penalty of course. Anyway with a good test case range checks can be off for speed when released.

I'll open new issues with some suggestions that maybe you can implement.

**Comment by dezlov** [comment]
Types `TTZHour`, `TTZMinute`, `TTZSecond` are used only inside `TimeToSeconds`. Their purpose is to raise range checking errors when some unexpected value is encountered, which is what happened with "24:00" notation.

The usable range has been expanded upstream (tzdata), so it is only proper that the range of `TTZHour` is also expanded to allow 0..24. This has no effect on the operation of the library, it will behave the same no matter the range of `TTZHour`.

However, I will also add an option (enabled by default) to check that time value is in range 00:00:00 to 24:00:00. `TTZHour` and other range types will be used only if the strict range is enforced, so there won't be any compiler generated range errors.

Appropriate test cases will be added.

**Comment by JoshyFun** [comment]
Glups!, Too many time from my side without looking at the original code, you are right, I was originally thinking in write the TTZDateTime record as year[-nnn..+nnnn], month [1..12] day [1..31] Hour [0..23] Minute [0..59] Second [0..60] but for some reason I left it without range checkings.
