### ISSUE TITLE
Fix ReloadDatebasePath on Unix OS

### ISSUE THREAD

**Issue by Al-Muhandis** [dezlov/pascaltz#6]
Please check request #5 

> On Unix, passing a directory name will result in True with FileExists function (because directory is file too in Unix). So it's valid to check if is really file not directory.
> Perhaps it's more beautiful to just put a check on the directory at the beginning, but I'm not sure if this matches the logic of the code. That is it is possible and so, it is possible
> ```
> if DirectoryExists(FDatabasePath) then
>   ParseDatabaseFromDirectory(FDatabasePath)
> else if FileExists(FDatabasePath) then
>   ParseDatabaseFromFile(FDatabasePath)
> ```

P.S. Thanks for awesome and useful lib!

**Comment by dezlov** [comment]
Thank you for reporting this issue.

It should be fixed in https://github.com/dezlov/PascalTZ/commit/f7f04914477d446200f5ccff34d532652e2ad5b9, please check.

**Comment by Al-Muhandis** [comment]
Thank you
