### ISSUE TITLE
Parse error "25:00" Hours component "25" is out of range.

### ISSUE THREAD

**Issue by unihedron** [dezlov/pascaltz#7]
I am getting this error with the latest 2018g timezone database file:

Parse error at line 3422: "Rule	Japan	1948	1951	-	Sep	Sat>=8	25:00	0	S" [Failed to parse time string "25:00" with error: Hours component "25" is out of range.].

**Comment by dezlov** [comment]
Thanks for reporting. This will be rectified shortly.

For the reference, relevant changes from the NEWS file in tzdata:

> **Release 2018g - 2018-10-26 22:22:45 -0700**
> 
> The translator to rearguard format now rewrites the line
> "Rule Japan 1948 1951 - Sep Sat>=8 25:00 0 S" to
> "Rule Japan 1948 1951 - Sep Sun>=9  1:00 0 S".
> This caters to zic before 2007 and to Oracle TZUpdater 2.2.0
> and earlier.  (Reported by Christos Zoulas.)
> 
> **Release 2018f - 2018-10-18 00:14:18 -0700**
> 
> The 1948-1951 fallback transitions in Japan were at 25:00 on
> September's second Saturday, not at 24:00.  (Thanks to Phake Nick.)
> zic turns this into 01:00 on the day after September's second
> Saturday, which is the best that POSIX or C platforms can do.

**Comment by unihedron** [comment]
Thank you for your quick reply!

There is one more error that I noticed:
  Parse error at line 8216: "
  1:00	-1:00	GMT	1947 Feb 23  2:00" [Rule on Zone  line "   1:00 -1:00 GMT 1947 Feb 23  2:00" not found.].

I worked around this by commenting out line 995 in the europe timezone file:
   1:00	-1:00	GMT	1947 Feb 23  2:00

**Comment by dezlov** [comment]
> There is one more error that I noticed:
> Parse error at line 8216: "
> 1:00 -1:00 GMT 1947 Feb 23 2:00" [Rule on Zone line " 1:00 -1:00 GMT 1947 Feb 23 2:00" not found.].

Yes, the parser is giving out about an unknown notation - fixed negative DST offset in Zone definition.

This will be rectified in ticket #8.
