### ISSUE TITLE
Zone info not found for link FROM "America/Los_Angeles" TO "US/Pacific-New"

### ISSUE THREAD

**Issue by unihedron** [dezlov/pascaltz#9]
I am getting this now when `pacificnew` is used:

> Parse error at line 29: "Link	America/Los_Angeles	US/Pacific-New	##" [Zone info not found for link FROM "America/Los_Angeles" TO "US/Pacific-New".].

PS. Thank you for fixing the other errors so quickly!

**Comment by dezlov** [comment]
It appears that you are not loading the timezone files in the correct order.

Basically, `pacificnew` depends on `backward` which in turn depends on other primary files.

Something like this will do the trick:

```
ParseDatabaseFromFiles([
    TZ_FILE_CONTINENT_AFRICA,
    TZ_FILE_CONTINENT_ANTARCTICA,
    TZ_FILE_CONTINENT_ASIA,
    TZ_FILE_CONTINENT_AUSTRALASIA,
    TZ_FILE_CONTINENT_EUROPE,
    TZ_FILE_CONTINENT_NORTHAMERICA,
    TZ_FILE_CONTINENT_SOUTHAMERICA,
    TZ_FILE_OTHER_BACKWARD,
    TZ_FILE_OTHER_ETCETERA,
    TZ_FILE_OTHER_PACIFICNEW
]);
```

Also, note that `pacificnew` is an obsolete file and will probably be removed in future versions of tzdata.

**Comment by unihedron** [comment]
Thank you! I have modified my code and the problem is gone.
